# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Cmod-S7-25-Master.xdc

# Block Designs: bd/Clock_Config/Clock_Config.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clock_Config || ORIG_REF_NAME==Clock_Config} -quiet] -quiet

# IP: bd/Clock_Config/ip/Clock_Config_clk_wiz_0_0/Clock_Config_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clock_Config_clk_wiz_0_0 || ORIG_REF_NAME==Clock_Config_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/dominick/Vivado/piezo_testplatform_1.0/piezo_testplatform_1.0.gen/sources_1/bd/Clock_Config/Clock_Config_ooc.xdc
